// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GestionDeCompteBancaire;

import java.util.Scanner;
import java.lang.String;
import java.util.Date;

public class CompteCourant extends CompteBancaire {

	public String nom;
	public String prenom;
	public long id;
	public Long numCompte;
	public String typeCompte;

	public void afficherCompte() {
		
		CompteCourant uneCourant = new CompteCourant();
		
		uneCourant.creerCompte();
		
		System.out.println("Votre nom est : " + nom);
		System.out.println("Votre prenom est : " + prenom);
		System.out.println("Votre date de naissance est : " + DateDeNaissance);
		System.out.println("Votre sex est : " + sex);
		System.out.println("Votre adresse est : " + adresse);
		System.out.println("Votre numero de compte est : " + numCompte);
		System.out.println("Votre type de compte est : " + typeCompte);
				
	}

	
	public void supprimerCompte(String n) {
		
          String cle = n;
		
		System.out.println("Entrer le numero du compte que vous souhaitez supprimer");
		Scanner sc = new Scanner(System.in);
		
		
         if (cle != null) {
			
			System.out.println(n + " a été supprimé ");
		}
		else System.out.println(n + " est inconnu ! ");
		
	}
	
    public int crediter(int montant) {
		
		int solde = 0;
		
		 solde += montant;
		 return solde;
		
	}
	
    public int debiter(int montant) {
		
		int solde = 0;
		
		 solde -= montant;
		 return solde;
		
	}

	
	public void ligneComptable() {
		
		int montant;
		String date;
		
		System.out.print("Entrer la montant à créditer (+) ou à débiter (-) : ");
		Scanner i = new Scanner(System.in);
		montant = i.nextInt();
		
		System.out.print("Entrer la Date de l'opération [jj/mm/an] ");
		Scanner f = new Scanner(System.in);
		date = f.nextLine();
	}

	public void afficherSolde() {
		
		int diffsolde;
		int solde = 0;
		
		diffsolde = solde - solde;
		
		System.out.println("La difference du solde est " + solde);
	}
};
