// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GestionDeCompteBancaire;

import java.util.Scanner;
import java.lang.String;
import java.util.Date;

public class CompteBancaire {
	
	public static final String Epargne = null;
	public static final  String Courant = null;
	public static final String Joint = null;
	public String nom;
	public String prenom;
	public String DateDeNaissance;
	public String sex;
	public String adresse;
	private String numCompte;
	private String typeCompte;
	
	public String getnumCompte() {
		
		return numCompte;
	}
	
	public String gettypeCompte() {
		
		return typeCompte;
	}

	public void afficherCompte() {
		
		CompteBancaire uneCompte = new CompteBancaire();
		
		System.out.println("Votre nom est : " + nom);
		System.out.println("Votre prenom est : " + prenom);
		System.out.println("Votre date de naissance est : " + DateDeNaissance);
		System.out.println("Votre sex est : " + sex);
		System.out.println("Votre adresse est : " + adresse);
		System.out.println("Votre numero de compte est : " + numCompte);
		
	}

	public void creerCompte() {
		
		Scanner in = new Scanner(System.in);
		
		int montant;
		int taux;
		
		System.out.println("Entrer votre nom");
		nom = in.next();
		
		System.out.println("Entrer votre prenom");
		prenom = in.next();
		
		System.out.println("Entrer votre date de naissance");
		DateDeNaissance = in.next();
		
		System.out.println("Entrer votre sex");
		sex = in.next();
		
		System.out.println("Entrer votre adresse");
		adresse = in.next();
		
		System.out.println("Entrer votre numero de compte");
		numCompte = in.next();
		verifier(numCompte);	
		
		if (typeCompte == Epargne) {
			
			System.out.println("Taux de placement");
			Scanner h = new Scanner(System.in);
			taux = h.nextInt();
			
		}
		
	}

	public void supprimerCompte(String n) {
		
		String cle = n;
		
		System.out.println("Entrer le numero du compte que vous souhaitez supprimer");
		Scanner sc = new Scanner(System.in);
		n = sc.next();
		
		if (cle != null) {
			
			System.out.println(n + " a été supprimé ");
		}
		else System.out.println(n + " est inconnu ! ");
		
	}

	public  int crediter(int montant) {
		
		int solde = 0;
		
		 solde = solde + montant;
		 return solde;
		
	}
	
    public  int debiter(int montant) {
    	
    	int solde = 0;
		
		 solde = solde - montant;
		 return solde;
		
	}
	
	public void ligneComptable() {
		
		int montant;
		String date;
		
		System.out.print("Entrer la montant à créditer (+) ou à débiter (-) : ");
		Scanner i = new Scanner(System.in);
		montant = i.nextInt();
		
		System.out.print("Entrer la Date de l'opération [jj/mm/an] : ");
		Scanner f = new Scanner(System.in);
		date = f.nextLine();
		
	}

	public void afficherSolde() {
		
		int diffsolde;
		int solde = 0;
		
		diffsolde = solde - solde;
		
		System.out.println("La difference du solde est " + solde);
		
	}
	
	public static boolean verifier(String numCompte) {
		
		////////// convert input to integer///////
		
		int[] creditCard = new int[numCompte.length()];
		
		for (int i = 0; i < numCompte.length(); i++)
		{
			creditCard[i] = Integer.parseInt(numCompte.substring(i, i + 1));
		}
		
		///////////Starting from the right,double each digit,if greater than 9,mod 10 and add 1 to the remainder//////////////
		
		for (int i = creditCard.length - 2; i >= 0; i = i - 2)
		{
			int tempValue = creditCard[i];
			tempValue = tempValue * 2;
			if (tempValue > 9)
			{
				tempValue = tempValue % 10 + 1;
			}
			
			creditCard[i] = tempValue;
		}
		
		/////////////////Add all digits/////////////////
		
		int total = 0;
		
		for (int i = 0; i < creditCard.length; i++)
		{
			total += creditCard[i];
		}
			
		/////////////////// if number is a multiple of 10,it is valid////////////////
		
		if (total % 10 == 0)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
};
